title: mondeja
email: mondejar1994@gmail.com
description: Álvaro Mondéjar Rubio's personal blog and portfolio
baseurl: /blog
url: http://mondeja.github.io
encoding: utf-8
timezone: Europe/Madrid

# Author
author:
  name: Álvaro Mondéjar Rubio
  email: mondejar1994@gmail.com
  github_username: mondeja
  bitbucket_username: mondeja
  stackexchange_id: 12547690
  telegram_username: amondejar
  twitter_username:
  facebook_username:
  linkedin_username:
  meetup_name:

# Jekyll configuration
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
exclude: [
  'scripts',
  'vendor',
  'README.md',
  'LICENSE',
  'Rakefile',
  'Gemfile',
  'Gemfile.lock',
  'package-lock.json'
]

# Internacionalization
languages: ["en", "es", "fr"]
default_locale_in_subfolder: true
exclude_from_localizations: [
  "assets/css",  # does not work in `_includes/*.html` files (see `scripts/build.rb`)
  "assets/js",
  "assets/fonts",
  "assets/img",
]

# Web services
google_analytics: UA-XXXXXX-X

# Directories
dir:
  files: /assets/files

# Asset filenames configuration
assets:
  # relative from files folder (site.dir.files)
  cv: cv-es.pdf
